### ISSUE TITLE
Undefined variable $temp

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#86]
While debugging an issue with the JSON fights feed implementation, I ran into an "undefined variable $temp" error in Event->assignGroups.

This appears to occur on a default install of PHP 7 and higher.

The cause is $temp being unset() and then no free groups exist.

I am preparing a patch for this.

**Comment by cjsoftuk** [comment]
Full stack trace for reference:

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: temp'

in /opt/antlog/models/Event.php:193

Stack trace:
#0 /opt/antlog/models/Event.php(193): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/opt/antlog/mod...', 193, Array)
#1 /opt/antlog/models/Event.php(118): app\models\Event->assignGroups(Array, '../fights/index...', 4, Object(app\models\ProgressBar))
#2 /opt/antlog/commands/EventController.php(30): app\models\Event->setupEvent('5aa050406dac6', '', '7', Array, '../fights/index...')
#3 [internal function]: app\commands\EventController->actionSetup('5aa0504283d13', '7', '../fights/index...', '')
#4 /opt/antlog/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /opt/antlog/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#6 /opt/antlog/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('setup', Array)
#7 /opt/antlog/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('setup', Array)
#8 /opt/antlog/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('event/setup', Array)
#9 /opt/antlog/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('event/setup', Array)
#10 /opt/antlog/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /opt/antlog/yii(23): yii\base\Application->run()
#12 {main}
```

**Comment by GaryA** [comment]
Fixed by merging cjsoftuk's hotfix :)
